#file1 = open(r'D:\Python Code\test\abc.txt','r',encoding='gbk') 
file1 = open('D:\\Python Code\\test\\abc.txt','r',encoding='utf-8')
filecontent = file1.read()
print(filecontent)
file1.close()

file1 = open(r'D:\Python Code\test\abc.txt','a',encoding='utf-8')
file1.write('张无忌\n')
file1.write('宋青书\n')
file1.close()